--查看表空间文件文职
SELECT NAME
FROM   V$DATAFILE;

--（查版本）  
SELECT *
FROM   V$VERSION;

--(查编码字符集)
SELECT USERENV('LANGUAGE')
FROM   DUAL;

--(查表空间与相 关联的用户) 

--创建新的表空间
--CREATE TABLESPACE DANYUAN_SPACE DATAFILE 'D:\oraclexe\oradata\XE\danyuan.ORA' SIZE 10M AUTOEXTEND ON;
CREATE TABLESPACE DANYUAN_SPACE
--LOGGING
DATAFILE 'D:\oraclexe\oradata\XE\danyuan.ORA' SIZE 1M AUTOEXTEND ON NEXT 2M MAXSIZE 50M EXTENT MANAGEMENT LOCAL;

--查看表空间大小
SELECT A.TABLESPACE_NAME,
			 A.BYTES / 1024 / 1024 "Sum MB",
			 (A.BYTES - B.BYTES) / 1024 / 1024 "used MB",
			 B.BYTES / 1024 / 1024 "free MB",
			 ROUND(((A.BYTES - B.BYTES) / A.BYTES) * 100,
						 2) "percent_used"
FROM   (SELECT TABLESPACE_NAME,
							 SUM(BYTES) BYTES
				FROM   DBA_DATA_FILES
				GROUP  BY TABLESPACE_NAME) A,
			 (SELECT TABLESPACE_NAME,
							 SUM(BYTES) BYTES,
							 MAX(BYTES) LARGEST
				FROM   DBA_FREE_SPACE
				GROUP  BY TABLESPACE_NAME) B
WHERE  A.TABLESPACE_NAME = B.TABLESPACE_NAME
ORDER  BY ((A.BYTES - B.BYTES) / A.BYTES) DESC;

--查看最大空间
SELECT FILE_NAME,
			 TABLESPACE_NAME,
			 BYTES / 1024 / 1024 "bytes MB",
			 MAXBYTES / 1024 / 1024 "maxbytes MB"
FROM   DBA_DATA_FILES
--WHERE  TABLESPACE_NAME = 'DANYUAN_SPACE'
;

-- 查看是否自动扩展
SELECT FILE_ID,
			 FILE_NAME,
			 TABLESPACE_NAME,
			 AUTOEXTENSIBLE,
			 INCREMENT_BY
FROM   DBA_DATA_FILES
ORDER  BY FILE_ID DESC;

-- 修改表空间增加表空间文件

--删除表空间
DROP TABLESPACE DANYUAN_SPACE;
--删除表空间(表空间非空)
DROP TABLESPACE DANYUAN_SPACE INCLUDING CONTENTS;
--删除表空间(表空间关联的表同时删除)
DROP TABLESPACE DANYUAN_SPACE INCLUDING CONTENTS AND DATAFILES;
--删除表空间(表空间关联的表置空)
DROP TABLESPACE DANYUAN_SPACE INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

--------------------------------------------用户创建权限的授予-------------------------------------------
/*以下操作需要用管理员登陆*/

--创建新用户
CREATE USER DANYUAN IDENTIFIED BY DANYUAN;
CREATE USER DANYUAN IDENTIFIED BY DANYUAN DEFAULT TABLESPACE DANYUAN_SPACE;
--CREATE USER DANYUAN IDENTIFIED BY DANYUAN DEFAULT TABLESPACE DANYUAN_SPACE TEMPORARY TABLESPACE DANYUAN_SPACE;（为什么不好用）

--给用户授予权限

GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY VIEW, CREATE ANY INDEX, CREATE ANY PROCEDURE, ALTER ANY TABLE, ALTER ANY PROCEDURE, DROP ANY TABLE, DROP ANY VIEW, DROP ANY INDEX, DROP ANY PROCEDURE,
	SELECT ANY    TABLE,
				 INSERT ANY TABLE,
				 UPDATE ANY TABLE,
				 DELETE ANY TABLE TO DANYUAN;
--将ROLE这个角色授与USERNAME, 也就是说，使USERNAME这个用户可以管理和使用ROLE所拥有的资源

GRANT ROLE TO USERNAME;

--DCL语句：数据控制语言，用户权限管理操作
--授权语句
--grant 权限1，权限2，……to 用户;
--收权语句
--revoke 权限1，权限2，…… from 用户;

--普通开发人员权限
GRANT CONNECT, RESOURCE TO DANYUAN;
GRANT CREATE VIEW TO DANYUAN;

--管理员权限
GRANT DBA TO DANYUAN;

--修改密码
ALTER USER DANYUAN IDENTIFIED BY DANYUAN2;

--解锁用户
ALTER USER DANYUAN ACCOUNT UNLOCK;

--加锁用户
ALTER USER DANYUAN ACCOUNT LOCK;

--导出某个用户的所有数据库对象，在纯命令行下执行以下命令
EXP ROOT / ROOT FILE = E :DANYUAN.DMP;

--删除用户
DROP USER DANYUAN CASCADE;

-----------------------------------------------查看用户权限---------------------------------------------------------

--查看所有用户

SELECT *
FROM   DBA_USERS
ORDER  BY USERNAME;
SELECT *
FROM   ALL_USERS
ORDER  BY USERNAME;
SELECT *
FROM   USER_USERS
ORDER  BY USERNAME;
--查看用户系统权限

SELECT *
FROM   DBA_SYS_PRIVS
ORDER  BY GRANTEE,
					PRIVILEGE;
SELECT *
FROM   USER_SYS_PRIVS
ORDER  BY USERNAME,
					PRIVILEGE;
--查看用户对象或角色权限

SELECT *
FROM   DBA_TAB_PRIVS
ORDER  BY GRANTEE;
SELECT *
FROM   ALL_TAB_PRIVS;
SELECT *
FROM   USER_TAB_PRIVS;
--查看所有角色

SELECT *
FROM   DBA_ROLES;
--查看用户或角色所拥有的角色

SELECT *
FROM   DBA_ROLE_PRIVS
ORDER  BY GRANTEE;
SELECT *
FROM   USER_ROLE_PRIVS;

----------------------------------ORACLE 删除用户及空闲表空间释放空间-----------------------------------
--分类： Oracle
--第一步：删除过期用户
DROP USER COLIN CASCADE;

--第二步：查询过期用户相关的表空间是否还有对象
SELECT OWNER,
			 SEGMENT_NAME,
			 SEGMENT_TYPE,
			 TABLESPACE_NAME
FROM   DBA_SEGMENTS
WHERE  TABLESPACE_NAME IN
			 (SELECT TABLESPACE_NAME
				FROM   DBA_TABLESPACES
				WHERE  TABLESPACE_NAME LIKE '%COLIN%') ；

--第三步：转移过期用户表空间上的对象到其他表空间
 ALTER TABLE TAB_COLIN MOVE TABLESPACE COLIN_SONG_TBS;

ALTER INDEX IDX_TAB_COLIN REBUILD TABLESPACE COLIN_SONG_IDX_TBS;

--第四步：查询无对象的表空间
SELECT 'DROP TABLESPACE ' || TABLESPACE_NAME ||
			 ' INCLUDING CONTENTS AND DATAFILES;'
FROM   DBA_TABLESPACES
WHERE  NOT EXISTS (SELECT 12
				FROM   DBA_SEGMENTS
				WHERE  DBA_SEGMENTS.TABLESPACE_NAME =
							 DBA_TABLESPACES.TABLESPACE_NAME);

--第五步：删除之 把上述查询出来的语句贴到文本编辑里检查下（PS:这里会包含一个temp的临时表空间一定要去掉啊)
DROP TABLESPACE STAT_FTFY_CHRGSTAY_DTBS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE STAT_FTFY_CHRGNEW_WIXTBS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE STAT_FTFY_CHRGSMR_MIXTBS INCLUDING CONTENTS AND DATAFILES;

---------------------------Oracle10g数据文件太大，导致C盘空间不够用的解决方法(重未试过)-------------------------
--1.先登录sqlplus：

--2.修改表空间为Offline：
ALTER TABLESPACE USERS OFFLINE;

--3.拷贝表空间文件
--拷贝
--E:\TaoCode\trunk\danyuan.ORA
--到
--D:\oraclexe\oradata\XE\danyuan.ORA

--4.修改oracle表空间指向地址
SQL > ALTER DATABASE RENAME FILE 'E:\TaoCode\trunk\danyuan.ORA' TO 'D:\oraclexe\oradata\XE\danyuan.ORA';

--5.修改表空间为Online
ALTER TABLESPACE USERS ONLINE;

--------------------------------------数据库迁移--------------------------------

--1.命令行cmd
--2.导出danyuan用户下的数据 (FILE = E\:DANYUAN.DMP)
EXP DANYUAN / DANYUAN@DANYUAN FILE = E :DANYUAN.DMP
--将数据库table1，table表导出
EXP DANYUAN / DANYUAN@DANYUAN FILE = E :DANYUAN.DMP TABLES =(TABLE1,
																														 TABLE2);
--3导入(FILE = E\:DANYUAN.DMP)
IMP DANYUAN / DANYUAN FILE = E :DANYUAN.DMP;
--倒入table1
IMP DANYUAN / DANYUAN FILE = E :DANYUAN.DMP TABLES =(TABLE1);

------------------------------------------------------------------------------------

